### ISSUE TITLE
UglifyJs fails with ES6 code in lib/Matrix2D.js

### ISSUE THREAD

**Issue by olivTo** [thelonious/kld-affine#13]
UglifyJs fails with E6 let declarations l129, 130, 143 and 144. 

Is it possible to use only ES5 features and replace "let" by "var" ?
Uglyfy will work fine with this changes. 

Thank you

**Comment by thelonious** [comment]
I'd like to move to even more ES6 constructs. I don't use uglify, but I see they have a "harmony" branch for ES6:

- https://github.com/mishoo/UglifyJS2/tree/harmony

Is that a possibility for you?

**Comment by olivTo** [comment]
Thank you. I'd used Babel to convert in ES5, so it's fine.
