### ISSUE TITLE
Point, vector, and matrix are not extensible

### ISSUE THREAD

**Issue by brandonpayton** [thelonious/kld-affine#3]
Thanks for creating and publishing this library. I've been experimenting with a game based on immutable data structures in my off hours, and kld-affine is just what I was looking for.

I would like to create a subtype of Point2D (so points can be used as keys in an Immutable.js map). At first, it seemed like it would be no problem, but if I create an instance of my subtype and call `Point2D#add`, the method returns an instance of `Point2D` rather than an instance of my subtype.

What do you think of updating the operation methods to use `new this.constructor(...)` instead of direct constructor references like `new Point2D(...)` so subtypes can take advantage of the base type's methods? If you're open to it, I am up for submitting a PR. _Note: Because of a recent job change, I'll need to get permission to contribute, but it shouldn't be a problem._

**Comment by thelonious** [comment]
That sounds like a great addition! A PR would be great (against development branch, please). If permission is an issue, I can make those changes; however, I'd prefer that you get proper attribution for the changes.

**Comment by brandonpayton** [comment]
Thanks! I've obtained permission, and a PR is forthcoming.
